remote_theme: mmistakes/minimal-mistakes
title: David Eduardo MORENO VILLAMARIN
description: Compturer Vision Engineer
logo: "img/my-vcard.png"

social-network-links:
  rss: true
  email: "david.moreno@ieee.org"
  github: ujemd
