remote_theme             : "mmistakes/minimal-mistakes@4.17.1"
minimal_mistakes_skin    : "contrast"

# Site settings
title                    : David Eduardo MORENO VILLAMARIN
subtitle                 : Compturer Vision Engineer
description: Compturer Vision Engineer
logo: "img/my-vcard.png"

links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
      url: mailto:david.moreno@ieee.org
    - label: "Website"
      icon: "fas fa-fw fa-link"
      url: "ujemd.github.com"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/ujemd?tab=repositories"

# Outputting
permalink: /:categories/:title/

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache
