remote_theme             : "mmistakes/minimal-mistakes@4.17.1"
minimal_mistakes_skin    : "contrast"

# Site settings
title                    : David Eduardo MORENO VILLAMARIN
subtitle                 : Compturer Vision Engineer
description: Compturer Vision Engineer
logo: "img/my-vcard.png"

links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
      url: mailto:david.moreno@ieee.org
    - label: "Website"
      icon: "fas fa-fw fa-link"
      url: "ujemd.github.com"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/ujemd?tab=repositories"

# Outputting
permalink: /:categories/:title/

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache

# Archives
#  Type
#  - GitHub Pages compatible archive pages built with Liquid ~> type: liquid (default)
#  - Jekyll Archives plugin archive pages ~> type: jekyll-archives
#  Path (examples)
#  - Archive page should exist at path when using Liquid method or you can
#    expect broken links (especially with breadcrumbs enabled)
#  - <base_path>/tags/my-awesome-tag/index.html ~> path: /tags/
#  - <base_path>/categories/my-awesome-category/index.html ~> path: /categories/
#  - <base_path>/my-awesome-category/index.html ~> path: /
category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
  
  # Defaults
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: # true
      share: true
      related: true
